# Site settings
title: 太匆匆，无奈朝来寒雨晚来风
label: 匆匆
email: 1158670354@qq.com
description: >
  While there is life, there is hope.
baseurl: "" # the subpath of your site
url: "" # the base hostname & potrocol for your site
twitter_username:
github_username:

# Build settings
markdown: kramdown
