# Site settings
title: 太匆匆，无奈朝来寒雨晚来风
label1: 匆匆
label2:
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  While there is life, there is hope.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
